addTeamPlayer: "Ajouter joueur equipe "
addPlayer: "Ajouter joueur"
back: "Retour"
day: "Jour "
daySelection: "Choix du jour"
startGame: "Démarrer la partie"
stopGame: "Arrêter la partie"
pauseGame: "Pauser la partie"
resumeGame: "Résumer la partie"
game: "Jeu"
rules: "Règles"
teams: "Equipes"
team: "Equipe"
pvpDay: "Jour PVP"
netherDay: "Jour Nether"
assaultDay: "Jour Assauts"
enderDay: "Jour End"
friendlyFire: "Tir Ami"
enderAssault: "Assaut à la perle de l'end"
healthBelowName: "Vie des joueurs visible"
respawnAtHome: "Respawn à la base"
disablePotions: "Potions"
tntJump: "TNT Jump"
teamBlue: "Equipe bleu"
teamRed: "Equipe rouge"
teamYellow: "Equipe jaune"
teamGreen: "Equipe verte"
teamRandom: "Equipe aléatoire"