// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: queuemanager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{0}
}

type QueuePlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Player uuid
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Game type to join
	Game string `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	// Map to join, use * for any map
	Map string `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
}

func (x *QueuePlayerRequest) Reset() {
	*x = QueuePlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePlayerRequest) ProtoMessage() {}

func (x *QueuePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePlayerRequest.ProtoReflect.Descriptor instead.
func (*QueuePlayerRequest) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{1}
}

func (x *QueuePlayerRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *QueuePlayerRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *QueuePlayerRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

type QueuePlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Is player queued or not
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Reason for queue fail if any
	Reason *string `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
}

func (x *QueuePlayerResponse) Reset() {
	*x = QueuePlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePlayerResponse) ProtoMessage() {}

func (x *QueuePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePlayerResponse.ProtoReflect.Descriptor instead.
func (*QueuePlayerResponse) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{2}
}

func (x *QueuePlayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueuePlayerResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type DequeuePlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID of the player to dequeue
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *DequeuePlayerRequest) Reset() {
	*x = DequeuePlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeuePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeuePlayerRequest) ProtoMessage() {}

func (x *DequeuePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeuePlayerRequest.ProtoReflect.Descriptor instead.
func (*DequeuePlayerRequest) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{3}
}

func (x *DequeuePlayerRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DequeuePlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Is player dequeued or not
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Reason for dequeue fail if any
	Reason *string `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
}

func (x *DequeuePlayerResponse) Reset() {
	*x = DequeuePlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeuePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeuePlayerResponse) ProtoMessage() {}

func (x *DequeuePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeuePlayerResponse.ProtoReflect.Descriptor instead.
func (*DequeuePlayerResponse) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{4}
}

func (x *DequeuePlayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DequeuePlayerResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type IsQueuedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID of the player to check
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *IsQueuedRequest) Reset() {
	*x = IsQueuedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsQueuedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsQueuedRequest) ProtoMessage() {}

func (x *IsQueuedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsQueuedRequest.ProtoReflect.Descriptor instead.
func (*IsQueuedRequest) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{5}
}

func (x *IsQueuedRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Queue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game    string   `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Map     string   `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
	Players []string `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *Queue) Reset() {
	*x = Queue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{6}
}

func (x *Queue) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *Queue) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *Queue) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type IsQueuedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Is player queued or not
	Queued bool `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
}

func (x *IsQueuedResponse) Reset() {
	*x = IsQueuedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsQueuedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsQueuedResponse) ProtoMessage() {}

func (x *IsQueuedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsQueuedResponse.ProtoReflect.Descriptor instead.
func (*IsQueuedResponse) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{7}
}

func (x *IsQueuedResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

type GetAllQueuesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queues []*Queue `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
}

func (x *GetAllQueuesResponse) Reset() {
	*x = GetAllQueuesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queuemanager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllQueuesResponse) ProtoMessage() {}

func (x *GetAllQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queuemanager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllQueuesResponse.ProtoReflect.Descriptor instead.
func (*GetAllQueuesResponse) Descriptor() ([]byte, []int) {
	return file_queuemanager_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllQueuesResponse) GetQueues() []*Queue {
	if x != nil {
		return x.Queues
	}
	return nil
}

var File_queuemanager_proto protoreflect.FileDescriptor

var file_queuemanager_proto_rawDesc = []byte{
	0x0a, 0x12, 0x71, 0x75, 0x65, 0x75, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x4e, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x61, 0x70, 0x22, 0x57, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2a, 0x0a,
	0x14, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x15, 0x44, 0x65, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x0f, 0x49, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x05, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x22, 0x2a, 0x0a, 0x10, 0x49, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64,
	0x22, 0x3c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x06, 0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x32, 0xa7,
	0x02, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x0d, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08,
	0x49, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x73, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x6d, 0x69, 0x6e, 0x6b,
	0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_queuemanager_proto_rawDescOnce sync.Once
	file_queuemanager_proto_rawDescData = file_queuemanager_proto_rawDesc
)

func file_queuemanager_proto_rawDescGZIP() []byte {
	file_queuemanager_proto_rawDescOnce.Do(func() {
		file_queuemanager_proto_rawDescData = protoimpl.X.CompressGZIP(file_queuemanager_proto_rawDescData)
	})
	return file_queuemanager_proto_rawDescData
}

var file_queuemanager_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_queuemanager_proto_goTypes = []interface{}{
	(*Empty)(nil),                 // 0: proto.Empty
	(*QueuePlayerRequest)(nil),    // 1: proto.QueuePlayerRequest
	(*QueuePlayerResponse)(nil),   // 2: proto.QueuePlayerResponse
	(*DequeuePlayerRequest)(nil),  // 3: proto.DequeuePlayerRequest
	(*DequeuePlayerResponse)(nil), // 4: proto.DequeuePlayerResponse
	(*IsQueuedRequest)(nil),       // 5: proto.IsQueuedRequest
	(*Queue)(nil),                 // 6: proto.Queue
	(*IsQueuedResponse)(nil),      // 7: proto.IsQueuedResponse
	(*GetAllQueuesResponse)(nil),  // 8: proto.GetAllQueuesResponse
}
var file_queuemanager_proto_depIdxs = []int32{
	6, // 0: proto.GetAllQueuesResponse.queues:type_name -> proto.Queue
	1, // 1: proto.QueueManagerService.QueuePlayer:input_type -> proto.QueuePlayerRequest
	3, // 2: proto.QueueManagerService.DequeuePlayer:input_type -> proto.DequeuePlayerRequest
	5, // 3: proto.QueueManagerService.IsQueued:input_type -> proto.IsQueuedRequest
	0, // 4: proto.QueueManagerService.GetAllQueues:input_type -> proto.Empty
	2, // 5: proto.QueueManagerService.QueuePlayer:output_type -> proto.QueuePlayerResponse
	4, // 6: proto.QueueManagerService.DequeuePlayer:output_type -> proto.DequeuePlayerResponse
	7, // 7: proto.QueueManagerService.IsQueued:output_type -> proto.IsQueuedResponse
	8, // 8: proto.QueueManagerService.GetAllQueues:output_type -> proto.GetAllQueuesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_queuemanager_proto_init() }
func file_queuemanager_proto_init() {
	if File_queuemanager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_queuemanager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuePlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuePlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeuePlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeuePlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsQueuedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Queue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsQueuedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queuemanager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllQueuesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_queuemanager_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_queuemanager_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queuemanager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queuemanager_proto_goTypes,
		DependencyIndexes: file_queuemanager_proto_depIdxs,
		MessageInfos:      file_queuemanager_proto_msgTypes,
	}.Build()
	File_queuemanager_proto = out.File
	file_queuemanager_proto_rawDesc = nil
	file_queuemanager_proto_goTypes = nil
	file_queuemanager_proto_depIdxs = nil
}
