apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agones_reader
rules:
  - apiGroups:
      - agones.dev
    resources:
      - gameservers
    verbs:
      - get
      - list
      - watch