apiVersion: v1
kind: Service
metadata:
  name: autoscaler-webhook-service
  labels:
    app: autoscaler-webhook
spec:
  selector:
    app: autoscaler-webhook
  ports:
    - port: 8080
      protocol: TCP
      name: https
      targetPort: autoscaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-webhook
  namespace: default
  labels:
    app: autoscaler-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler-webhook
  template:
    metadata:
      labels:
        app: autoscaler-webhook
    spec:
      containers:
        - name: autoscaler-webhook
          image: minki-autoscaler:latest
          imagePullPolicy: Never
          ports:
            - name: autoscaler
              containerPort: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5