// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: mappy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map     string `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Game    string `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetMapRequest) Reset() {
	*x = GetMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapRequest) ProtoMessage() {}

func (x *GetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapRequest.ProtoReflect.Descriptor instead.
func (*GetMapRequest) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{0}
}

func (x *GetMapRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *GetMapRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *GetMapRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map *Map `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
}

func (x *GetMapResponse) Reset() {
	*x = GetMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse) ProtoMessage() {}

func (x *GetMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse.ProtoReflect.Descriptor instead.
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{1}
}

func (x *GetMapResponse) GetMap() *Map {
	if x != nil {
		return x.Map
	}
	return nil
}

type UploadMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map        string `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Game       string `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	MinPlayers int32  `protobuf:"varint,3,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers int32  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	ZipPath    string `protobuf:"bytes,5,opt,name=zipPath,proto3" json:"zipPath,omitempty"`
	Version    string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *UploadMapRequest) Reset() {
	*x = UploadMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMapRequest) ProtoMessage() {}

func (x *UploadMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMapRequest.ProtoReflect.Descriptor instead.
func (*UploadMapRequest) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMapRequest) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *UploadMapRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *UploadMapRequest) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *UploadMapRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *UploadMapRequest) GetZipPath() string {
	if x != nil {
		return x.ZipPath
	}
	return ""
}

func (x *UploadMapRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UploadMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UploadMapResponse) Reset() {
	*x = UploadMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMapResponse) ProtoMessage() {}

func (x *UploadMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMapResponse.ProtoReflect.Descriptor instead.
func (*UploadMapResponse) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{3}
}

func (x *UploadMapResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMapsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game string `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *ListMapsRequest) Reset() {
	*x = ListMapsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapsRequest) ProtoMessage() {}

func (x *ListMapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapsRequest.ProtoReflect.Descriptor instead.
func (*ListMapsRequest) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{4}
}

func (x *ListMapsRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Map        string `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
	Game       string `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	MinPlayers int32  `protobuf:"varint,4,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers int32  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Data       []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Version    string `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Map) Reset() {
	*x = Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{5}
}

func (x *Map) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Map) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *Map) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *Map) GetMinPlayers() int32 {
	if x != nil {
		return x.MinPlayers
	}
	return 0
}

func (x *Map) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *Map) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Map) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListMapsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maps []*Map `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty"`
}

func (x *ListMapsResponse) Reset() {
	*x = ListMapsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapsResponse) ProtoMessage() {}

func (x *ListMapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapsResponse.ProtoReflect.Descriptor instead.
func (*ListMapsResponse) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{6}
}

func (x *ListMapsResponse) GetMaps() []*Map {
	if x != nil {
		return x.Maps
	}
	return nil
}

type GetRandomMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game string `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *GetRandomMapRequest) Reset() {
	*x = GetRandomMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomMapRequest) ProtoMessage() {}

func (x *GetRandomMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomMapRequest.ProtoReflect.Descriptor instead.
func (*GetRandomMapRequest) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{7}
}

func (x *GetRandomMapRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type GetRandomMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map *Map `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
}

func (x *GetRandomMapResponse) Reset() {
	*x = GetRandomMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mappy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomMapResponse) ProtoMessage() {}

func (x *GetRandomMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mappy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomMapResponse.ProtoReflect.Descriptor instead.
func (*GetRandomMapResponse) Descriptor() ([]byte, []int) {
	return file_mappy_proto_rawDescGZIP(), []int{8}
}

func (x *GetRandomMapResponse) GetMap() *Map {
	if x != nil {
		return x.Map
	}
	return nil
}

var File_mappy_proto protoreflect.FileDescriptor

var file_mappy_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x61, 0x70, 0x70, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70,
	0x52, 0x03, 0x6d, 0x61, 0x70, 0x22, 0xae, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x67, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x69, 0x70, 0x50, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61,
	0x6d, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x67, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x32, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x04,
	0x6d, 0x61, 0x70, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22,
	0x34, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70,
	0x52, 0x03, 0x6d, 0x61, 0x70, 0x32, 0x93, 0x02, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x70, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70,
	0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4d, 0x61, 0x70, 0x12,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4d, 0x61, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x61, 0x70, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x6d,
	0x69, 0x6e, 0x6b, 0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x79, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mappy_proto_rawDescOnce sync.Once
	file_mappy_proto_rawDescData = file_mappy_proto_rawDesc
)

func file_mappy_proto_rawDescGZIP() []byte {
	file_mappy_proto_rawDescOnce.Do(func() {
		file_mappy_proto_rawDescData = protoimpl.X.CompressGZIP(file_mappy_proto_rawDescData)
	})
	return file_mappy_proto_rawDescData
}

var file_mappy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mappy_proto_goTypes = []interface{}{
	(*GetMapRequest)(nil),        // 0: proto.GetMapRequest
	(*GetMapResponse)(nil),       // 1: proto.GetMapResponse
	(*UploadMapRequest)(nil),     // 2: proto.UploadMapRequest
	(*UploadMapResponse)(nil),    // 3: proto.UploadMapResponse
	(*ListMapsRequest)(nil),      // 4: proto.ListMapsRequest
	(*Map)(nil),                  // 5: proto.Map
	(*ListMapsResponse)(nil),     // 6: proto.ListMapsResponse
	(*GetRandomMapRequest)(nil),  // 7: proto.GetRandomMapRequest
	(*GetRandomMapResponse)(nil), // 8: proto.GetRandomMapResponse
}
var file_mappy_proto_depIdxs = []int32{
	5, // 0: proto.GetMapResponse.map:type_name -> proto.Map
	5, // 1: proto.ListMapsResponse.maps:type_name -> proto.Map
	5, // 2: proto.GetRandomMapResponse.map:type_name -> proto.Map
	0, // 3: proto.MappyService.GetMap:input_type -> proto.GetMapRequest
	7, // 4: proto.MappyService.GetRandomMap:input_type -> proto.GetRandomMapRequest
	4, // 5: proto.MappyService.ListMaps:input_type -> proto.ListMapsRequest
	2, // 6: proto.MappyService.UploadMap:input_type -> proto.UploadMapRequest
	1, // 7: proto.MappyService.GetMap:output_type -> proto.GetMapResponse
	8, // 8: proto.MappyService.GetRandomMap:output_type -> proto.GetRandomMapResponse
	6, // 9: proto.MappyService.ListMaps:output_type -> proto.ListMapsResponse
	3, // 10: proto.MappyService.UploadMap:output_type -> proto.UploadMapResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mappy_proto_init() }
func file_mappy_proto_init() {
	if File_mappy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mappy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMapsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMapsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mappy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mappy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mappy_proto_goTypes,
		DependencyIndexes: file_mappy_proto_depIdxs,
		MessageInfos:      file_mappy_proto_msgTypes,
	}.Build()
	File_mappy_proto = out.File
	file_mappy_proto_rawDesc = nil
	file_mappy_proto_goTypes = nil
	file_mappy_proto_depIdxs = nil
}
